#!/bin/bash

echo "🚀 eng.com Environment Setup"
echo "=============================="

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists. Creating backup..."
    cp .env.local .env.local.backup.$(date +%Y%m%d-%H%M%S)
fi

# Create .env.local with template
cat > .env.local << 'EOF'
# ===========================================================================
# eng.com Environment Configuration
# ===========================================================================
# Generated by setup-env.sh script
# Update the values below with your actual credentials

# ===========================================================================
# SUPABASE CONFIGURATION (REQUIRED)
# ===========================================================================
# Get these from: https://app.supabase.com/project/[your-project]/settings/api
NEXT_PUBLIC_SUPABASE_URL=https://your-project-ref.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.your-actual-anon-key
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.your-actual-service-role-key

# ===========================================================================
# AUTHENTICATION CONFIGURATION (REQUIRED)
# ===========================================================================
NEXTAUTH_SECRET=temp-dev-secret-change-in-production
NEXTAUTH_URL=http://localhost:4000

# ===========================================================================
# OAUTH PROVIDERS (Optional)
# ===========================================================================
# GOOGLE_CLIENT_ID=your-google-client-id.apps.googleusercontent.com
# GOOGLE_CLIENT_SECRET=your-google-client-secret
# GITHUB_CLIENT_ID=your-github-client-id
# GITHUB_CLIENT_SECRET=your-github-client-secret

# ===========================================================================
# STRIPE CONFIGURATION (Optional)
# ===========================================================================
# STRIPE_PUBLISHABLE_KEY=pk_test_your-stripe-publishable-key
# STRIPE_SECRET_KEY=sk_test_your-stripe-secret-key
# STRIPE_WEBHOOK_SECRET=whsec_your-stripe-webhook-secret

# ===========================================================================
# DEVELOPMENT SETTINGS
# ===========================================================================
NODE_ENV=development
DEBUG=true
EOF

echo "✅ Created .env.local file"
echo ""
echo "📋 NEXT STEPS:"
echo "1. Open .env.local in your editor"
echo "2. Replace the Supabase URLs and keys with your actual values"
echo "3. If you don't have Supabase set up yet, run: npm run setup:supabase"
echo "4. Generate a secure NextAuth secret: openssl rand -base64 32"
echo ""
echo "🔧 To use temporary local Supabase (for testing only):"
echo "   Run: npm run setup:local-supabase"
echo ""
echo "⚠️  WARNING: Do not commit .env.local to version control!"

# Check if git is configured to ignore .env.local
if ! grep -q ".env.local" .gitignore 2>/dev/null; then
    echo ".env.local" >> .gitignore
    echo "✅ Added .env.local to .gitignore"
fi 